#!/usr/bin/env python3
"""Generate TypeScript interfaces from the FastAPI OpenAPI schema."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = PROJECT_ROOT / "frontend/src/lib/types/generated-api.ts"


def ts_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return repr(str(value))


def schema_to_ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return ts_name(schema["$ref"])

    if "const" in schema:
        return literal(schema["const"])

    if "enum" in schema:
        return " | ".join(literal(item) for item in schema["enum"])

    if "anyOf" in schema:
        return " | ".join(schema_to_ts(item) for item in schema["anyOf"])

    if "oneOf" in schema:
        return " | ".join(schema_to_ts(item) for item in schema["oneOf"])

    if "allOf" in schema:
        return " & ".join(schema_to_ts(item) for item in schema["allOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(schema_to_ts({**schema, "type": item}) for item in schema_type)

    if schema_type == "string":
        return "string"
    if schema_type == "null":
        return "null"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        return f"{schema_to_ts(schema.get('items', {}))}[]"
    if schema_type == "object" or "properties" in schema:
        additional = schema.get("additionalProperties")
        if additional and additional is not True:
            return f"Record<string, {schema_to_ts(additional)}>"
        if additional is True and not schema.get("properties"):
            return "Record<string, unknown>"
        properties = schema.get("properties", {})
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = []
        for name, prop_schema in properties.items():
            optional = "" if name in required else "?"
            fields.append(f"  {name}{optional}: {schema_to_ts(prop_schema)}")
        return "{\n" + "\n".join(fields) + "\n}"

    return "unknown"


def render_schema(name: str, schema: dict[str, Any]) -> str:
    if schema.get("type") == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        properties = schema.get("properties", {})
        lines = [f"export interface {name} {{"]
        if not properties and schema.get("additionalProperties"):
            lines.append("  [key: string]: unknown")
        for prop_name, prop_schema in properties.items():
            optional = "" if prop_name in required else "?"
            lines.append(f"  {prop_name}{optional}: {schema_to_ts(prop_schema)}")
        lines.append("}")
        return "\n".join(lines)

    return f"export type {name} = {schema_to_ts(schema)}"


def generate_types() -> str:
    sys.path.insert(0, str(PROJECT_ROOT))
    from api.main import app

    schemas = app.openapi().get("components", {}).get("schemas", {})
    blocks = [
        "// Generated by scripts/generate_openapi_types.py. Do not edit by hand.",
        "",
    ]
    for name in sorted(schemas):
        blocks.append(render_schema(name, schemas[name]))
        blocks.append("")
    return "\n".join(blocks).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    generated = generate_types()

    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != generated:
            print(f"{args.output} is out of date. Run scripts/generate_openapi_types.py")
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
